export const FILTER_CUSTOM_TABLE = "FILTER_CUSTOM_TABLE";
export const MODAL_FLAG = "MODAL_FLAG";
export const MODAL_CUSTOM_FLAG = "MODAL_CUSTOM_FLAG";
export const FIND_INDEX_OF_CUSTOMERS = "FIND_INDEX_OF_CUSTOMERS";
export const STOCK_PRICE_CHANGES = 'STOCK_PRICE_CHANGES';
export const SHOULD_UPDATE_TABLE = 'SHOULD_UPDATE_TABLE';